// Code generated by "stringer -type=Family -output=string.go"; DO NOT EDIT.

package wgipam

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IPv4-1]
	_ = x[IPv6-2]
	_ = x[DualStack-3]
}

const _Family_name = "IPv4IPv6DualStack"

var _Family_index = [...]uint8{0, 4, 8, 17}

func (i Family) String() string {
	i -= 1
	if i < 0 || i >= Family(len(_Family_index)-1) {
		return "Family(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Family_name[_Family_index[i]:_Family_index[i+1]]
}
