# wgipamd vALPHA configuration file

# The storage backend for IP address allocations and leases.
#
# If none specified, ephemeral in-memory storage will be used.
[storage]
file = "/var/lib/wgipamd"

# Specify one or more WireGuard interfaces to listen on for IP
# assignment requests.
[[interfaces]]
name = "wg0"

# Optional: the amount of time a lease will exist before it expires, specified
# in Go time.ParseDuration format (https://golang.org/pkg/time/#ParseDuration).
# If not set or empty, defaults to 1 hour.
lease_duration = "1h"

  # Specify one or more IPv4 and/or IPv6 subnets to allocate addresses from.
  [[interfaces.subnets]]
  subnet = "192.0.2.0/24"
  # Optional: specify a range of addresses within the subnet which will be
  # used for leases. For example, this can be used to skip over statically
  # allocated peer addresses before or after this range.
  #
  # Both start and end are optional and either may be omitted to use the
  # first and last addresses in a range.
  #
  # Addresses in this range can be individually excluded by adding them
  # to the reserved list for this subnet.
  start = "192.0.2.10"
  end = "192.0.2.255"
  # Optional: specify individual addresses within the subnet which are
  # reserved and will not be used for leases. For example, this can be
  # used to reserve certain addresses for static peer allocations.
  reserved = [
    "192.0.2.255"
  ]

  [[interfaces.subnets]]
  subnet = "2001:db8::/64"
  # Optional: see above.
  reserved = [
    "2001:db8::",
    "2001:db8::1"
  ]

# Enable or disable the debug HTTP server for facilities such as Prometheus
# metrics and pprof support.
#
# Warning: do not expose pprof on an untrusted network!
[debug]
address = "localhost:9475"
prometheus = true
pprof = false
